### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by miname**
## I verified my work is based on `develop` branch
* [x] yes, keep going

## Purpose of this Pull Request?
To make Korean users happy. 👍 

## Where should the reviewer start its review?
A new file titled as *"contrast-finder_utf8_ko.properties"* added.

## How the PR could be tested?
No breaking changes, I hope.

## Any background context you want to provide?
**There are two paragraphs(line no. 51 and 57) where its usage is unknown.** So I just left it untouched. Could you tell me in what context the phrase being used?

### CODE REVIEW

**Comment by mfaure** [comment]
Wouaw, awesome! Great job @miname! Thank you very much. @dzc34 will surely integrate this in the next release.

**Comment by dzc34** [comment]
@miname, thank you very much. Integrated this in the new release. 
https://app.contrast-finder.org/?lang=ko

**Comment by dzc34** [comment]
> There are two paragraphs(line no. 51 and 57) where its usage is unknown. So I just left it untouched. Could you tell me in what context the phrase being used? 

see  #88

**Comment by dzc34** [comment]
#88 is now fixed
and available in the last release
https://forum.asqatasun.org/t/contrast-finder-new-release-v0-8-1-korean-translation/357

**Pull request merged**
